version: '3'
services:
  fedora-cygwin-host:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./workspace:/mnt/workspace
      - ./tmp:/tmp
    network_mode: "bridge"
    privileged: true
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    tmpfs:
      - /run
      - /run/lock
    hostname: fedora-cygwin-host
    cap_add:
      - ALL
    stdin_open: true
    tty: true
