#!/bin/bash

echo 'Running post-install script'

# system environment variables
echo 'container=docker' >> /etc/environment
echo 'LC_ALL=C' >> /etc/environment
echo 'LANG="C.UTF-8"' >> /etc/environment

cat /tmp/fch_i/4 >> /etc/environment
cp /tmp/fch_i/4 /etc/profile.d/proxy.sh
chmod +x /etc/profile.d/proxy.sh

cp -avf /etc/environment /etc/environment.original

echo 'Installing extra sysroot for rust build'

tar -v -C /usr/x86_64-pc-cygwin/sys-root -x -f /tmp/fch_i/5/sysroot-rust-build.tgz

echo 'Installing toshimaru/nyan'

wget https://ghproxy.com/https://github.com/toshimaru/nyan/releases/latest/download/nyan_Linux_x86_64.tar.gz -O /tmp/nyan.tgz

tar -C /usr/local/bin -x -f /tmp/nyan.tgz nyan

chmod +x /usr/local/bin/nyan

echo 'Setting mirror for pip'

python3 -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

su fedora -c 'HOME=/home/fedora python3 -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple'

systemctl disable sshd
