#!/bin/bash

echo 'Running post-install script'

# system environment variables
echo 'container=docker' >> /etc/environment
echo 'LC_ALL=C' >> /etc/environment
echo 'LANG="C.UTF-8"' >> /etc/environment

cat /tmp/fch_i/4 >> /etc/environment
cp /tmp/fch_i/4 /etc/profile.d/proxy.sh
chmod +x /etc/profile.d/proxy.sh

cp -avf /etc/environment /etc/environment.original

echo 'Installing extra sysroot for rust build'

tar -v -C /usr/x86_64-pc-cygwin/sys-root -x -f /tmp/fch_i/5/sysroot-rust-build.tgz

systemctl disable sshd
